; Script generated by the Inno Setup Script Wizard.
; FlatAV by Suyandi

[Setup]
AppName=FlatAV
AppVerName=FlatAV 1.0
AppPublisher=Suyandi Wu
DefaultDirName={pf}\FlatAV
DefaultGroupName=FlatAV
LicenseFile=FlatAV\lgpl.txt
OutputDir=.
OutputBaseFilename=FlatAVsetup
Compression=lzma
SolidCompression=yes
VersionInfoVersion=1.0.0.0
VersionInfoCopyright=2008 Suyandi Wu
; uninstall icon in add / remove program
UninstallDisplayIcon={app}\FlatAVGUI.exe

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
Source: "FlatAV\FlatAVGUI.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "FlatAV\main.fvd"; DestDir: "{app}"; Flags: ignoreversion
Source: "FlatAV\libflatav.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "FlatAV\ShellCtl.dll"; DestDir: "{app}"; Flags: ignoreversion regserver
; these two files should be supplied manually depending on your build setting and visual studio version
Source: "FlatAV\mfc90u.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "FlatAV\msvcr90.dll"; DestDir: "{app}"; Flags: ignoreversion


[Icons]
Name: "{group}\FlatAV"; Filename: "{app}\FlatAVGUI.exe"; WorkingDir: "{app}"
Name: "{group}\Uninstall FlatAV"; Filename: "{uninstallexe}";
Name: "{commondesktop}\FlatAV"; Filename: "{app}\FlatAVGUI.exe"; WorkingDir: "{app}"; Tasks: desktopicon

[Registry]
Root: HKCU; Subkey: "Software\SuyandiWu\FlatAV"; Flags: uninsdeletekeyifempty
Root: HKCU; Subkey: "Software\SuyandiWu\FlatAV"; ValueType: string; ValueName: "InstallFolder"; ValueData: "{app}"



